[[pages]]
path = "painel_despesas.py"
name = "AnÃ¡lise de Despesas"
icon = "ğŸ’¸"


[[pages]]
path = "painel_receitas.py"
name = "AnÃ¡lise de Receitas"
icon = "ğŸ’°"


[[pages]]
path = "painel_faturamentos.py"
name = "AnÃ¡lise dos Faturamentos"
icon = "ğŸ§¾"


[[pages]]
path = "painel_valuation.py"
name = "Valuation"
icon = "ğŸ¤‘"


[[pages]]
path = "painel_llc.py"
name = "Century Data LLC"
icon = "ğŸ‡ºğŸ‡¸"